name: Publish Python ğŸ
on: push

jobs:
  build-n-publish:
    name: Publish â›ˆï¸â›ˆï¸  pystorms â›ˆï¸ â›ˆï¸  to pypi ğŸ“¦ 
    runs-on: ubuntu-18.04
    steps:
    - name: Publish distribution ğŸ“¦ to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
